name: Deploy Bridgetown site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2" # dostosuj do własnych potrzeb

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Node dependencies
        run: npm install

      - name: Build CSS with Tailwind
        run: npm run build

      - name: Copy built CSS to Bridgetown assets
        run: cp frontend/styles/index.css src/_assets/css/main.css

      - name: Build Bridgetown site
        run: bundle exec bridgetown build

      - name: Copy CSS to output/assets
        run: |
          mkdir -p output/assets
          cp frontend/styles/index.css output/assets/main.css

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
